stages: #定义步骤列表类型，从上往下执行
  - install
  - build
  - dep

cache: #缓存
  paths:
    - node_modules
    - dist

install-job:
  stage: install
  script:
    - npm install 
    # --registry=https://r.cnpmjs.org
  tags: #选择runner的tag
    - runner

build-job:
  stage: build
  script:
    - npm run build
  after_script:
    - echo '成功'
  tags: #选择runner的tag
    - runner
  only:
    - master


dep-job:
  stage: dep
  script:
    - echo '成功'
  tags: #选择runner的tag
    - runner
  only:
    - master