stages: #定义步骤列表类型，从上往下执行
  - install
  
install-job:
  stage: install
  before_script:
    - yarn
  script:
    - npm run build
  after_script:
    - echo '成功'
    # --registry=https://r.cnpmjs.org
  tags: #选择runner的tag
    - runner