stages: #定义步骤列表类型，从上往下执行
  - install
  - build
  - deploy
cache: #缓存
  paths:
    - node_modules
    - dist
install-job:
  stage: install
  script:
    - npm install
build-job: #job名字
  stage: build #和stages对应的名字
  image: #i.harbor.xxxx.com/public/node:10-alpine-node-sass  #使用的镜像，如果不写，就是注册runner默认镜像
  script:
    - npm run build
  tags: #选择runner的tag
    - master
  #only: #构建选择，如下，只选择develop的分支构建
   # - master
deploy-job:
  stage: deploy
  tags:
    - master
  scripts:
    - echo '成功'
