stages: #定义步骤列表类型，从上往下执行
  - install
  - build
  - deploy

cache: #缓存
  paths:
    - node_modules
    - dist

install-job:
  stage: install
  script:
    - npm install --registry=https://r.cnpmjs.org

build-job:
  stage: build
  script:
    - npm run build
  tags: #选择runner的tag
    - runner
  only:
    - master

deploy:
  stage: deploy
  tags:
    - runner
  scripts:
    - echo '成功'
   only:
    - master
