name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.1
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm run build
        
      - name: Cache pnpm-store
        uses: actions/cache@v3.3.1
        with:
          path: node_modules/
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
        
      - name: Deploy
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SOURCE: dist/
          SCRIPT_BEFORE: rm -rf /www/wwwroot/https/assets/
          ARGS: -rlgoDzvc -i --ignore-times
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_HOST: ${{ secrets.HOST }}
          TARGET: ${{ secrets.REMOTE_PATH }}
